services:
  - type: web
    name: nspxn-ai-review
    runtime: python
    plan: starter
    build:
      command: |
        # Install python dependencies
        pip install -r requirements.txt
    start:
      command: |
        # Install system packages
        apt-get update && \
        apt-get install -y tesseract-ocr poppler-utils && \
        uvicorn main:app --host 0.0.0.0 --port $PORT
